
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql1-pv-claim
  labels:
    app: mysql1-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql2-pv-claim
  labels:
    app: mysql2-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql3-pv-claim
  labels:
    app: mysql3-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysql1
    tier: mysqlcluster
  name: mysql1
spec:
  hostname: mysql1
  securityContext:
    runAsUser: 0
  containers:
  - image: stefanos87/mysqlclusterdb1
    name: mysql1
    ports:
      - containerPort: 3306
      - containerPort: 33060
    volumeMounts:
      - mountPath: "/var/lib/mysql"
        name: mysql1  
    resources:
      requests:
        cpu: 100m
        memory: 600Mi
    livenessProbe:
      exec:
        command: ["mysqladmin", "ping"]
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
    readinessProbe:
      exec:
        # Check we can execute queries over TCP (skip-networking is off).
        command: ["mysql", "-u", "root", "-proot", "-e", "SELECT 1;" ]
      initialDelaySeconds: 5
      periodSeconds: 2
      timeoutSeconds: 1    
  volumes:
    - name: mysql1
      persistentVolumeClaim:
        claimName:  mysql1-pv-claim   
  dnsPolicy: ClusterFirst
  restartPolicy: Always

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysql2
    tier: mysqlcluster
  name: mysql2
spec:
  hostname: mysql2
  securityContext:
    runAsUser: 0
  containers:
  - image: stefanos87/mysqlclusterdb1
    name: mysql2
    ports:
      - containerPort: 3306
      - containerPort: 33060
    volumeMounts:
      - mountPath: "/var/lib/mysql"
        name: mysql2  
    resources:
      requests:
        cpu: 100m
        memory: 600Mi
    livenessProbe:
      exec:
        command: ["mysqladmin", "ping"]
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
    readinessProbe:
      exec:
        # Check we can execute queries over TCP (skip-networking is off).
        command: ["mysql", "-u", "root", "-proot", "-e", "SELECT 1;" ]
      initialDelaySeconds: 5
      periodSeconds: 2
      timeoutSeconds: 1    
  volumes:
    - name: mysql2
      persistentVolumeClaim:
        claimName:  mysql2-pv-claim   
  dnsPolicy: ClusterFirst
  restartPolicy: Always

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysql3
    tier: mysqlcluster
  name: mysql3
spec:
  hostname: mysql3
  securityContext:
    runAsUser: 0
  containers:
  - image: stefanos87/mysqlclusterdb1
    name: mysql3
    ports:
      - containerPort: 3306
      - containerPort: 33060
    volumeMounts:
      - mountPath: "/var/lib/mysql"
        name: mysql3  
    resources:
      requests:
        cpu: 100m
        memory: 600Mi
    livenessProbe:
      exec:
        command: ["mysqladmin", "ping"]
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
    readinessProbe:
      exec:
        # Check we can execute queries over TCP (skip-networking is off).
        command: ["mysql", "-u", "root", "-proot", "-e", "SELECT 1;" ]
      initialDelaySeconds: 5
      periodSeconds: 2
      timeoutSeconds: 1    
  volumes:
    - name: mysql3
      persistentVolumeClaim:
        claimName:  mysql3-pv-claim   
  dnsPolicy: ClusterFirst
  restartPolicy: Always  



---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql1
  name: mysql1
spec:
  ports:
    - name: mysql  
      port: 3306
      protocol: TCP
      targetPort: 3306
    - name: mysqlcluster  
      port: 33060
      protocol: TCP
      targetPort: 33060   
    - name: mysqlclusterconf  
      port: 33061
      protocol: TCP
      targetPort: 33061  
  selector:
    app: mysql1

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql2
  name: mysql2
spec:
  ports:
    - name: mysql  
      port: 3306
      protocol: TCP
      targetPort: 3306
    - name: mysqlcluster  
      port: 33060
      protocol: TCP
      targetPort: 33060     
    - name: mysqlclusterconf  
      port: 33061
      protocol: TCP
      targetPort: 33061   
  selector:
    app: mysql2

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql3
  name: mysql3
spec:
  ports:
    - name: mysql  
      port: 3306
      protocol: TCP
      targetPort: 3306
    - name: mysqlcluster  
      port: 33060
      protocol: TCP
      targetPort: 33060   
    - name: mysqlclusterconf  
      port: 33061
      protocol: TCP
      targetPort: 33061  
  selector:
    app: mysql3

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  ports:
    - name: mysql  
      port: 3306
      protocol: TCP
      targetPort: 3306  
  selector:
      tier: mysqlcluster

