apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysql1
    tier: mysqlcluster
  name: mysql1
spec:
  hostname: node1
  securityContext:
    runAsUser: 0
  containers:
  - image: stefanos87/mysqlclusterdb1
    name: mysql1
    ports:
      - containerPort: 3306
      - containerPort: 33060
    resources:
      requests:
        cpu: 50m
        memory: 200Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always

